-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 23, 2021 at 02:17 PM
-- Server version: 10.4.21-MariaDB
-- PHP Version: 8.0.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `blog_submissions`
--

-- --------------------------------------------------------

--
-- Table structure for table `blog_sub`
--

CREATE TABLE `blog_sub` (
  `name` varchar(30) NOT NULL,
  `email` varchar(40) NOT NULL,
  `submission_type` varchar(20) NOT NULL,
  `title` varchar(60) NOT NULL,
  `content` longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `blog_sub`
--

INSERT INTO `blog_sub` (`name`, `email`, `submission_type`, `title`, `content`) VALUES
('Shravya', 'shravya@gmail.com', 'article', 'Health', 'In the 2020 Social Progress Index, which measures quality of life across the globe using 50 well-being metrics, Americans rated themselves worse off now than they were 10 years ago. This data was collected before the COVID-19 pandemic hit, which has only increased the nation’s need to live healthier, more balanced lives.<br />\r\n<br />\r\nAs we prepare to enter a new year, you may be considering spending more time working on health and wellness. You don’t necessarily need an expensive gym membership or a diet plan to improve your health. You can get solid health and wellness tips from authoritative blogs. The following are some of the top wellness blogs in areas of fitness, nutrition, and mental health.'),
('Robert Frost', 'robertfrost@gmail.com', 'poem', 'Road Not Taken', 'Two roads diverged in a yellow wood,<br />\r\nAnd sorry I could not travel both<br />\r\nAnd be one traveler, long I stood<br />\r\nAnd looked down one as far as I could<br />\r\nTo where it bent in the undergrowth;<br />\r\n<br />\r\nThen took the other, as just as fair,<br />\r\nAnd having perhaps the better claim,<br />\r\nBecause it was grassy and wanted wear;<br />\r\nThough as for that the passing there<br />\r\nHad worn them really about the same,<br />\r\n<br />\r\nAnd both that morning equally lay<br />\r\nIn leaves no step had trodden black.<br />\r\nOh, I kept the first for another day!<br />\r\nYet knowing how way leads on to way,<br />\r\nI doubted if I should ever come back.'),
('Vasudev', 'vasudev@gmail.com', 'poem', 'Me..', 'And what I assume you shall assume,<br />\r\nFor every atom belonging to me as good belongs to you.<br />\r\nI loafe and invite my soul,<br />\r\nI lean and loafe at my ease observing a spear of summer grass.<br />\r\n<br />\r\nMy tongue, every atom of my blood, form’d from this soil, this air,<br />\r\nBorn here of parents born here from parents the same, and their parents the<br />\r\npoem'),
('Rashmi Bhat A', 'rashmibhat@gmail.com', 'poem', 'This Is Not a Small Voice', 'This is not a small voice<br />\r\nyou hear               this is a large<br />\r\nvoice coming out of these cities.<br />\r\nThis is the voice of LaTanya.<br />\r\nKadesha. Shaniqua. This<br />\r\nis the voice of Antoine.<br />\r\nDarryl. Shaquille.<br />\r\nRunning over waters<br />\r\nnavigating the hallways<br />\r\nof our schools spilling out<br />\r\non the corners of our cities and<br />\r\nno epitaphs spill out of their river mouths.<br />\r\n<br />\r\nThis is not a small love<br />\r\nyou hear               this is a large<br />\r\nlove, a passion for kissing learning<br />\r\non its face.<br />\r\nThis is a love that crowns the feet with hands<br />\r\nthat nourishes, conceives, feels the water sails<br />\r\nmends the children,<br />\r\nfolds them inside our history where they<br />\r\ntoast more than the flesh<br />\r\nwhere they suck the bones of the alphabet<br />\r\nand spit out closed vowels.<br />\r\nThis is a love colored with iron and lace.<br />\r\nThis is a love initialed Black Genius.<br />\r\n<br />\r\nThis is not a small voice<br />\r\nyou hear.'),
('Shraddha Shetty', 'shradhashetty@gmail.com', 'poem', 'Dreams', 'Hold fast to dreams <br />\r\nFor if dreams die<br />\r\nLife is a broken-winged bird<br />\r\nThat cannot fly.<br />\r\n<br />\r\nHold fast to dreams<br />\r\nFor when dreams go<br />\r\nLife is a barren field<br />\r\nFrozen with snow.'),
('Swathi', 'swathi123@gmail.com', 'poem', 'Life is Fine', 'I went down to the river,<br />\r\nI set down on the bank.<br />\r\nI tried to think but couldn\'t,<br />\r\nSo I jumped in and sank.<br />\r\n<br />\r\nI came up once and hollered!<br />\r\nI came up twice and cried!<br />\r\nIf that water hadn\'t a-been so cold<br />\r\nI might\'ve sunk and died.<br />\r\n<br />\r\n     But it was      Cold in that water!      It was cold!<br />\r\n<br />\r\nI took the elevator<br />\r\nSixteen floors above the ground.<br />\r\nI thought about my baby<br />\r\nAnd thought I would jump down.<br />\r\n<br />\r\nI stood there and I hollered!<br />\r\nI stood there and I cried!<br />\r\nIf it hadn\'t a-been so high<br />\r\nI might\'ve jumped and died.<br />\r\n<br />\r\n     But it was      High up there!      It was high!<br />\r\n<br />\r\nSo since I\'m still here livin\',<br />\r\nI guess I will live on.<br />\r\nI could\'ve died for love—<br />\r\nBut for livin\' I was born<br />\r\n<br />\r\nThough you may hear me holler,<br />\r\nAnd you may see me cry—<br />\r\nI\'ll be dogged, sweet baby,<br />\r\nIf you gonna see me die.<br />\r\n<br />\r\n     Life is fine!      Fine as wine!      Life is fine!'),
('Sonika Shetty', 'sonikashetty@gmail.com', 'poem', 'Stopping by Woods on a Snowy Evening', 'Whose woods these are I think I know.<br />\r\nHis house is in the village, though;<br />\r\nHe will not see me stopping here<br />\r\nTo watch his woods fill up with snow.<br />\r\n<br />\r\nMy little horse must think it queer<br />\r\nTo stop without a farmhouse near<br />\r\nBetween the woods and frozen lake<br />\r\nThe darkest evening of the year.<br />\r\n<br />\r\nHe gives his harness bells a shake<br />\r\nTo ask if there is some mistake.<br />\r\nThe only other sound’s the sweep<br />\r\nOf easy wind and downy flake.<br />\r\n<br />\r\nThe woods are lovely, dark, and deep,<br />\r\nBut I have promises to keep,<br />\r\nAnd miles to go before I sleep,<br />\r\nAnd miles to go before I sleep.'),
('Shamitha Kumari', 'shamithakumari@gmail.com', 'poem', 'A Prayer in Spring', 'Oh, give us pleasure in the flowers to-day;<br />\r\nAnd give us not to think so far away<br />\r\nAs the uncertain harvest; keep us here<br />\r\nAll simply in the springing of the year.<br />\r\n<br />\r\nOh, give us pleasure in the orchard white,<br />\r\nLike nothing else by day, like ghosts by night;<br />\r\nAnd make us happy in the happy bees,<br />\r\nThe swarm dilating round the perfect trees.<br />\r\n<br />\r\nAnd make us happy in the darting bird<br />\r\nThat suddenly above the bees is heard,<br />\r\nThe meteor that thrusts in with needle bill,<br />\r\nAnd off a blossom in mid air stands still.<br />\r\n<br />\r\nFor this is love and nothing else is love,<br />\r\nThe which it is reserved for God above<br />\r\nTo sanctify to what far ends He will,<br />\r\nBut which it only needs that we fulfil.'),
('Dhanya K', 'dhanyak@gmail.com', 'article', 'Global Warming', 'Global warming is the long-term warming of the planet’s overall temperature. Though this warming trend has been going on for a long time, its pace has significantly increased in the last hundred years due to the burning of fossil fuels. <br />\r\nAs the human population has increased, so has the volume of fossil fuels burned. Fossil fuels include coal, oil, and natural gas, and burning them causes what is known as the “greenhouse effect” in Earth’s atmosphere. <br />\r\n<br />\r\nThe greenhouse effect is when the Sun’s rays penetrate the atmosphere, but when that heat is reflected off the surface cannot escape back into space. Gases produced by the burning of fossil fuels prevent the heat from leaving the atmosphere. These greenhouse gasses are carbon dioxide, chlorofluorocarbons, water vapor, methane, and nitrous oxide. The excess heat in the atmosphere has caused the average global temperature to rise overtime, otherwise known as global warming.<br />\r\n<br />\r\nGlobal warming has presented another issue called climate change. Sometimes these phrases are used interchangeably, however, they are different. Climate change refers to changes in weather patterns and growing seasons around the world. It also refers to sea level rise caused by the expansion of warmer seas and melting ice sheets and glaciers. Global warming causes climate change, which poses a serious threat to life on earth in the forms of widespread flooding and extreme weather. Scientists continue to study global warming and its impact on Earth.'),
('Dhanya K', 'dhanyak@gmail.com', 'poem', 'The Girl Stayed in her Room More and More Often', 'You do not understand her mother often said<br />\r\nHer father understood her but he was not home much<br />\r\nHer mother called her names; not nice ones.<br />\r\n<br />\r\nShe shrunk a little every time her mother spoke.<br />\r\nExpecting to be put down, cringing when she saw her mother.<br />\r\nShe stayed in her room<br />\r\n<br />\r\nDecorated in snowflakes,<br />\r\nThere was a reverence about it<br />\r\nIt was a sanctuary where she felt safe<br />\r\nShe stayed here more and more often<br />\r\nLearning that her own company was the best<br />\r\n<br />\r\nHer mother spouted religion at her in an angry way<br />\r\nTried to drag her to church, where she was a bigshot.<br />\r\nThe girl ignored her mother’s efforts,<br />\r\nWaited for her father to return home<br />\r\nBut he never did'),
('Dhanya K', 'dhanyak@gmail.com', 'article', 'ISRO', 'The Indian Space Research Organisation is the national space agency of India, headquartered in Bengaluru. It operates under the Department of Space (DOS) which is directly overseen by the Prime Minister of India, while Chairman of ISRO acts as executive of DOS as well. ISRO is the primary agency in India to perform tasks related to space based applications,<br />\r\n space exploration and development of related technologies. It is one of six government space agencies in the world which possess full launch capabilities, deploy cryogenic engines, launch extra-terrestrial missions and operate large fleets of artificial satellites.[7][8][b]<br />\r\n<br />\r\nThe Indian National Committee for Space Research (INCOSPAR) was established by Jawaharlal Nehru under the Department of Atomic Energy (DAE) in 1962, on the urging of scientist Vikram Sarabhai recognising the need in space research. INCOSPAR grew and became ISRO in 1969, within DAE.[9] In 1972, the Government of India had set up a Space Commission and the Department of Space (DOS), bringing ISRO under the DOS. The establishment of ISRO thus institutionalised space research activities in India. It since then has been managed by the DOS, which governs various other institutions in India in domain of astronomy and space technology'),
('Rashmi Bhat A', 'rashmibhat@gmail.com', 'story', 'VIJAY DIWAS', 'India celebrates Vijay Diwas on December 16 to commemorate its victory over Pakistan in the 1971 war, which led to the creation of Bangladesh. On this day, Indians pay homage to the brave soldiers of our country. The defining moments in the history of the subcontinent also established the prowess of the Indian Armed Forces including the Army, Air Force and Navy. Vijay Diwas 2021 marks the 51th anniversary celebrations of India’s victory over Pakistan in 1971.<br />\r\n<br />\r\nAfter fighting for 13 days, India won the war against Pakistan on December 16, 1971. During the struggle for independence in East Pakistan, the war started on December 3, 1971, and ended 13 days later on December 16 with the unconditional surrender of the Pakistan army.<br />\r\n<br />\r\nThe ‘Instrument of Surrender’ was signed and accepted by Lieutenant General Jagjit Singh Aurora, the then General Officer Commanding-in-Chief of India’s Eastern Command.<br />\r\n<br />\r\nAfter World War II, this was also the biggest-ever military surrender and the iconic picture of Niazi signing the ‘Instrument of Surrender’ tells the story about the bravery of the mighty Indian Army.<br />\r\n<br />\r\nIn this war, Pakistan suffered the maximum casualty with about 8,000 dead and 25,000 wounded, while India lost 3000 soldiers and 12,000 were injured.'),
('Rashmi Bhat A', 'RASHMIBHAT.AGRAHARA@GMAIL.COM', 'story', 'Ant And GrassHopper', 'One bright day in late autumn a family of Ants were bustling about in the warm sunshine, drying out the grain they had stored up during the summer, when a starving Grasshopper, his fiddle under his arm, came up and humbly begged for a bite to eat.<br />\r\n&quot;What!&quot; cried the Ants in surprise, &quot;haven\'t you stored anything away for the winter? What in the world were you doing all last summer?&quot;<br />\r\n&quot;I didn\'t have time to store up any food,&quot; whined the Grasshopper; &quot;I was so busy making music that before I knew it the summer was gone.&quot;<br />\r\nThe Ants shrugged their shoulders in disgust.<br />\r\n&quot;Making music, were you?&quot; they cried. &quot;Very well; now dance!&quot; And they turned their backs on the Grasshopper and went on with their work.'),
('Shravya V Shet', 'shravyav@gmail.com', 'article', 'Swatch Bharath Abhiyan', 'Swachh Bharat Abhiyan set a lot of objectives to achieve so that India could become cleaner and better. In addition, it not only appealed the sweepers and workers but all the citizens of the country. This helped in making the message reach wider. It aims to build sanitary facilities for all households. One of the most common problems in rural areas is that of open defecation. Swachh Bharat Abhiyan aims to eliminate that.<br />\r\nMoreover, the Indian government intends to offer all the citizens with hand pumps, proper drainage system, bathing facility and more. This will promote cleanliness amongst citizens.<br />\r\nSimilarly, they also wanted to make people aware of health and education through awareness programs. After that, a major objective was to teach citizens to dispose of waste mindfully.<br />\r\nIndia is in dire need of a cleanliness drive like Swachh Bharat Abhiyan to eradicate dirtiness. It is important for the overall development of citizens in terms of health and well-being. As the majority of the population of India lives in rural areas, it is a big problem.<br />\r\n<br />\r\nGenerally, in these areas, people do not have proper toilet facilities. They go out in the fields or roads to excrete. This practice creates a lot of hygiene problems for citizens. Therefore, this Clean India mission can be of great help in enhancing the living conditions of these people.<br />\r\nIn short, Swachh Bharat Abhiyan is a great start to make India cleaner and greener. If all the citizens could come together and participate in this drive, India will soon flourish. Moreover, when the hygienic conditions of India will improve, all of us will benefit equally. India will have more tourists visiting it every year and will create a happy and clean environment for the citizens'),
('Prathiksha', 'prathikshakotian@gmail.com', 'poem', 'Lets Preserve Nature', 'The sun is shining<br />\r\nThe sky is blue<br />\r\nThe birds are flying<br />\r\nAnd the breeze is so cool.<br />\r\n<br />\r\nMother Nature is trying her best<br />\r\nTo give nothing but beautifulness<br />\r\nBut what do we do?<br />\r\nMake her a mess.<br />\r\n<br />\r\nLet’s make her the best<br />\r\nBy polluting less and less<br />\r\nAnd preserve her green dress<br />\r\nFor our kids and the rest.');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
